### ISSUE TITLE
A HTTP error will cause Node.js  to exit (non-gracefully)

### ISSUE THREAD

**Issue by swijnands** [mollie/mollie-api-node#1]
If a HTTP error occurs (for whatever reason) during a Mollie API Request, Node.js exits, without a way for the end-user to catch the error, i.e.:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Parse Error
    at CleartextStream.socketOnData (http.js:1583:20)
    at CleartextStream.read [as _read] (tls.js:507:12)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:221:10)
    at writeOrBuffer (_stream_writable.js:211:5)
    at EncryptedStream.Writable.write (_stream_writable.js:180:11)
    at write (_stream_readable.js:583:24)
    at flow (_stream_readable.js:592:7)
    at Socket.pipeOnReadable (_stream_readable.js:624:5)
```

This can/should be prevented by adding a request.on('error', function(err) { .... }) handler, and calling the end-user callback function with the appropriate feedback, in the rest client:

https://github.com/mollie/mollie-api-node/blob/master/src/lib/mollie/api/client.coffee#L82-92

**Comment by arenddeboer** [comment]
Is this issue still present ? I am bit concerned about using the Mollie Node API in production while this bug exists.

**Comment by RicardoJ** [comment]
Hello @arenddeboer, this issue is still present, however, @Pagebakers created a pull request on April 1th, 2016 (#12) where this is been fixed. Take a look in the purposed pull request for more information.

**Comment by dabroek** [comment]
The fix in #12 was merged, but later reverted in https://github.com/mollie/mollie-api-node/commit/8b520f5ac19878f4a649f626cfc821a45fc7d2eb. This issue still needs to be addressed and resolved.

**Comment by dabroek** [comment]
#18 is addressing this issue.

**Comment by vernondegoede** [comment]
Please use our new `@mollie/api-client` module, which is completely rewritten to ES6 and fully tested.

You can find information on how to upgrade in our [Migration guide](https://github.com/mollie/mollie-api-node/blob/master/MIGRATION.md).
