### ISSUE TITLE
no debug mode 

### ISSUE THREAD

**Issue by Morriz** [mollie/mollie-api-node#10]
I can't find a way to start with DEBUG mode enabled. I suggest visionmedia's `debug` lib to sprinkle output whenever appropriate. It is now very hard to see what is going on under the hood.

**Comment by Thijs-Riezebeek** [comment]
Hi Morriz,

My apologies for not replying sooner to this issue. Is this still relevant?

**Comment by Morriz** [comment]
probably, if it's not fixed...but I am traveling
