### ISSUE TITLE
Implement Certifi package

### ISSUE THREAD

**Issue by vernondegoede** [mollie/mollie-api-node#100]

**Comment by martijnpolder** [comment]
I reviewed the [Certifi](https://certifi.io) package, it seems legit and accurately maintained. I'm greenlighting the use of this package to improve on our current CA update process.

**Comment by vernondegoede** [comment]
We cannot use the Certifi package _yet_, as it is outdated. 
I created a PR which should fix this issue: https://github.com/certifi/node-certifi/pull/5

**Comment by martijnpolder** [comment]
Let's only use it for Python for now, the other packages look abandoned

**Comment by firstred** [comment]
Node.js certifi version looks abandoned even.

Maybe download it automatically before a deploy to NPM?
https://curl.haxx.se/docs/caextract.html


We could extend `.travis.yml` like this:
```yaml
before_deploy:
  - curl --remote-name --time-cond cacert.pem https://curl.haxx.se/ca/cacert.pem ${TRAVIS_BUILD_DIR}/dist/cjs/cacert.pem
  - cp ${TRAVIS_BUILD_DIR}/dist/cjs/cacert.pem ${$TRAVIS_BUILD_DIR}/dist/esm/cacert.pem
```

**Comment by vernondegoede** [comment]
That won't work, as we also have to support manual releases (which at this moment is the only way to release a new version).
