### ISSUE TITLE
Nested Mollie calls receive weird responses / Concurrency problem?

### ISSUE THREAD

**Issue by DigitalLeaves** [mollie/mollie-api-node#104]
Hello,

I am running through a problem when trying to create a first recurring payment using the API in Node.js (version 2.1.1). This is my calling code:

```
mollie.payments.create({
      customerId: customerId,
      amount: { currency: 'EUR', value: amount.toFixed(2) }, 
      description: "description",
      redirectUrl: redirectionURL,
      dueDate: oneWeekFromNowString(),
      sequenceType: 'first',
      webhookUrl: MOLLIE_PAYMENTS_WEBHOOK_URL,
      metadata: { service_id: service._id, customer_id: customerId },
    }, function (err, molliePayment) {
		console.log("Got response:")
		console.log(err)
		console.log(molliePayment)
})
```

I get two responses: one proper response, with err null and a valid molliePayment, but a second response, immediately after that one, with both err and molliePayment set to null. That completely ruins the backend logic.

I have checked and this function is not being called twice, so the problem happens here. Any hint?

**Comment by vernondegoede** [comment]
@DigitalLeaves Will the callback be called twice when you modify the example to use a callback? When that's not the case, this isn't a problem with the Node.js API client.

```
/**
 * @docs https://docs.mollie.com/reference/v2/payments-api/create-payment
 */
const mollie = require("@mollie/api-client");
const mollieClient = mollie({ apiKey: "test_xxxx" });

const payment = mollieClient.payments.create(
  {
    amount: {
      currency: "EUR",
      value: "10.00" // You must send the correct number of decimals, thus we enforce the use of strings
    },
    description: "My first payment",
    redirectUrl: "https://webshop.example.org/order/12345/",
    webhookUrl: "https://webshop.example.org/payments/webhook/",
    metadata: {
      order_id: "12345"
    }
  },
  (err, molliePayment) => {
    console.log({ err, molliePayment });
  }
);
```

**Comment by DigitalLeaves** [comment]
Solved, it was my fault, as there's no Node.js documentation on the right way to call the method, I was doing it wrong. Thanks for sharing that. May I ask that this snippet is included in the documentation so other developers avoid finding the same problems in the future? Thanks! 🙏🏻

**Comment by DigitalLeaves** [comment]
While that works in a very

**Comment by DigitalLeaves** [comment]
I wonder why all your examples are synchronous where obviously mollie payments are designed for an asynchronous scenario (i.e: Node and Express).

**Comment by DigitalLeaves** [comment]
Ok, I figured out where's the problem. Mollie is not working properly when using nested calls in which the mollie module is called twice, meaning, there is probably some kind of thread/concurrency problem.

Let me put a reproducible example where it fails:
Mollie module mollie_payments.js :
```
...
const apiKey = "..."
const mollie = require('@mollie/api-client')({ apiKey: apiKey })

exports.retrieveCustomerMandates = function (customerId, callback) {
    try {
        console.log("*** 1")
        mollie.customers_mandates.all({customerId: customerId}, function (err, mandates) {
            console.log("*** 2")
            if (err || !mandates) {
                console.log("*** 3")
                var msg = "Error retrieving mandates". "
                if (err && err.message) { msg += err.message }
                return callback(new Error(msg))
            } else {
                console.log("*** 4")
                return callback(null, mandates)
            }
        })
    } catch (e) {
        console.log("*** 5")
        console.log("Fatal error!"); console.log(e)
        var msg = "Error retrieving mandates for customer "+customerId+". "
        if (e && e.message) { msg += e.message } else { msg += "Customer or mandates not found."}
        return callback(new Error(msg))
    }
}

exports.customerHasValidMandates = function (customerId, callback) {
    console.log("*** i")
    exports.retrieveCustomerMandates(customerId, function (err, mandates) {
        console.log("*** ii")
        if (err || !mandates) {
            console.log("*** iii")
            var msg = "Error getting customer mandates. "
            if (err && err.message) { msg += err.message }
            return callback (new Error(msg), false)
        } else {
            console.log("*** iv")
            var validMandate = false
            for (var i = 0; i < mandates.length; i++) {
                var mandate = mandates[i]
                if (mandate.hasOwnProperty('status') && mandate.status.toLowerCase() == kTuEmpresaEnEstoniaMollieMandateStatusValid) {
                    validMandate = true
                    break;
                }
            }
            return callback(null, validMandate)
        }
    })
}
...
```

And this is test.js module:

```
var molliePayments = require('./mollie_payments.js')
const customerId = "..."
console.log("Checking customer mandates...")
molliePayments.customerHasValidMandates(customerId, function (err, hasValidMandates) {
	console.log("Has valid mandates?")
	console.log(err)
	console.log(hasValidMandatess)

	if (err) { console.log("Not continuing... exiting...") }
	else {
		molliePayments.retrieveCustomerMandates(customerId, function (err, mandates) {
			console.log("So the mandates are...")
			console.log(err)
			console.log(mandates)
		})
	}
})
```

Expected results should be (for a customer with valid mandates):
```
Checking customer mandates...
*** i
*** ii
*** iv
Has valid mandates?
null
true
*** 1
*** 2
*** 4
So the mandates are...
null
[ ... ] // list of mandates here.
```

However, actual results are:
```
Checking customer mandates...
*** i
*** 1
*** 2
*** 4
*** ii
*** iv
Has valid mandates?
null
*** 2
*** 3
*** ii
*** iii
Has valid mandates?
Error: Error getting customer mandates. Error retrieving mandates for customer cst_XXXXXXXXXXXX. Customer or mandates not found.
    at /path/to/project/mollie_payments.js:218:30
    at /path/to/project/mollie_payments.js:195:24
    at Function.errorHandler (/path/to/project/node_modules/@mollie/api-client/dist/mollie.js:547:16)
    at /path/to/project/node_modules/@mollie/api-client/dist/mollie.js:483:25
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:29936) UnhandledPromiseRejectionWarning: ReferenceError: hasValidMandatess is not defined
    at /path/to/project/test.js:20:14
    at /path/to/project/mollie_payments.js:218:20
    at /path/to/project/mollie_payments.js:195:24
    at Function.errorHandler (/path/to/project/node_modules/@mollie/api-client/dist/mollie.js:547:16)
    at /path/to/project/node_modules/@mollie/api-client/dist/mollie.js:483:25
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:29936) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29936) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Calling `customerHasValidMandates` or `retrieveCustomerMandates` individually in non-nested calls work perfectly without any errors.

The same happens on every call where you need to do different nested calls depending on the result of the previous one. Notable examples include creating a first recurring payment, requiring you to a) create a customer and then b) create the payment with sequenceType = first.

**Comment by DigitalLeaves** [comment]
Hello, any news about this?

**Comment by vernondegoede** [comment]
Sorry for the late response. Your example code isn't entirely clear to me. There's a lot happening there, and names used in the `console.log` statements are a bit confusing. Also, there's a 

Anyway, if I understand you correctly, the goal of your code was to check whether there is a valid mandate (in the case a customer has multiple mandates) for a customer with a specific ID.

I tried to reproduce your issue using a slightly different and simplified approach (Promises), which can be found here: https://gist.github.com/vernondegoede/567fd39a2ad19a44fdf448c81c488552. Promises are the recommended way of doing this, as callbacks will be deprecated in the near future.

```bash
➜ ~/Sites/node-test-workspace node index.js
Checking whether customer cst_pzhEvnttJ2 has valid mandates
Checking whether customer cst_UK9ArCbc2K has valid mandates
No valid mandate found for customer cst_UK9ArCbc2K
Found mandate for customer cst_pzhEvnttJ2 Mandate {
  resource: 'mandate',
  id: 'mdt_yM4fQ4fvnW',
  status: 'valid',
  method: 'directdebit',
  details:
   { consumerName: 'John Doe',
     consumerAccount: 'NL55INGB0000000000',
     consumerBic: 'INGBNL2A' },
  mandateReference: 'YOUR-COMPANY-MD13804',
  signatureDate: '2018-05-07',
  createdAt: '2018-10-11T17:16:12+00:00',
  _links:
   { self:
      { href: 'https://api.mollie.com/v2/customers/cst_pzhEvnttJ2/mandates/mdt_yM4fQ4fvnW',
        type: 'application/hal+json' },
     customer:
      { href: 'https://api.mollie.com/v2/customers/cst_pzhEvnttJ2',
        type: 'application/hal+json' } },
  mode: 'test',
  customerId: 'cst_pzhEvnttJ2' }
```

As you can see in the output above, the calls are ran asynchronously without any problems.

I'm not sure why this would be a concurrency problem with the Node.js API client, as you only make a single call to the Mollie Node.js API client (the retrieving of the actual mandates).

**Comment by DigitalLeaves** [comment]
Again, that code works in toy examples like that, but not on a real Node.js/Express scenario. There's obviously a concurrency problem with the way you are managing promises. If I'm wrong, then point me to where my code is wrong. It should work, right?

Please forget about the meaning of the code snippet (it was a dumb example, but any other call to molliePayments will fail in the exact same way when nesting).

Happy to give you any files you may need. 

Thank you.

**Comment by DigitalLeaves** [comment]
Have you at least been able to reproduce it using the sample code I sent you? Happy to send a zip file if you need it.

**Comment by mattijsbliek** [comment]
We have, and unfortunately the problem is not with our Node client. I’m not 100% sure what is going wrong, but I slightly altered your code to make it work.

Sorry we can’t help further, I hope this resolves your issue 👏

```javascript
// test.js
const molliePayments = require('./mollie_payments2');
const customerId = 'CUSTOMER ID HERE';

molliePayments.customerHasValidMandates(customerId, function(
  err,
  hasValidMandates
) {
  if (err) {
    console.log('There was an error', err);
    return;
  }

  if (!hasValidMandates) {
    console.log('No valid mandates found');
    return;
  }

  console.log('Do we have a valid mandate? ', hasValidMandates);
  console.log('Now fetching the mandates again...');

  molliePayments.retrieveCustomerMandates(customerId, function(err, mandates) {
    console.log('So the mandates are...');
    console.log(err);
    console.log(mandates);
  });
});
```

```javascript
// mollie_payments.js
const apiKey = 'API KEY HERE';
const mollie = require('@mollie/api-client')({ apiKey: apiKey });

exports.retrieveCustomerMandates = function(customerId, callback) {
  console.log(`Getting all mandates from Mollie for customer ${customerId}`);
  mollie.customers_mandates.all(
    {
      customerId: customerId,
    },
    function(err, mandates) {
      if (err) {
        console.log(err);
        return;
      }
      console.log(`Fetched ${mandates.length} mandates`);
      callback(null, mandates);
    }
  );
};

exports.customerHasValidMandates = function(customerId, callback) {
  exports.retrieveCustomerMandates(customerId, function(err, mandates) {
    if (err) {
      callback(err);
      return;
    }

    var validMandate = false;
    for (var i = 0; i < mandates.length; i++) {
      var mandate = mandates[i];
      validMandate = true;
      break;
    }

    return callback(null, validMandate);
  });
};
```

**Comment by DigitalLeaves** [comment]
Dear @mattijsbliek,

If I may offer some feedback on this issue, and with due respect. I've been developing code for 20 years now. I know this ego and this attitude of "the problem is not with our Node client" (a.k.a "It's not our fault"). But how it cannot possibly be a problem of your node client when the code I sent you only does two calls to your API?

As you may understand, given that you don't have proper Node.js documentation apart from those examples, it makes it very difficult for us to develop using your API. Obviously, this sample code is not in our code. We spent some time putting together a small example. But this behavior is happening all over our code. So what should we do? Grant you access to our git repository so you guys can "tweak" every call where the Mollie API is not working properly? You didn't even mention what you have done to solve the issue or what should we modify.

Please take this as positive criticism. **I don't expect you to do anything else here.** As I mentioned, I've been there before, developing code and receiving support tickets. I know how it feels. But this is not open source. We are paying for using Mollie. And we are still stuck with a deadline for automating the payments of our platform, an API that's not working properly, and a support/development team who says "the problem is not with our Node client".

**Comment by vernondegoede** [comment]
Just ran into this issue myself as well. Pretty sure something is going wrong on this line and the reference to the original object is lost:

https://github.com/mollie/mollie-api-node/blob/master/src/resource.js#L177
