### ISSUE TITLE
What is the intended way to use the webhook verification?

### ISSUE THREAD

**Issue by marbuser** [mollie/mollie-api-node#109]
So, I've been playing around with this for a few days, and have ran into a bit of a wall.

It would seem the ability to distinguish paid transactions, refunds, and disputes all on the same webhook is incredibly complicated? Primarily due to the fact that the same object is always sent with no indication of what the action was?

Can't tell if I'm doing anything wrong, but after looking at the code, there is `isPaid` which I'd assume you'd use to check, well if a payment was paid... However, even on disputes and refunds this is true... So that can lead to duplication of "successful" responses.

I then noticed `isRefundable`. This doesn't seem to make any sense either. It checks "amountRemaining", but from my experience, "amountRemaining" it is always a random number? I made 3 payments each for €60, and all 3 of them returned different results inside of "amountRemaining", so I've got no idea what this is supposed to represent.

So am I just being stupid? If so, can someone please explain to me the "correct" way to check on a single webhook for the different statuses of; Payment Complete (Once! If it's called again it should not process), Refunds, and Disputes. Because I've been playing around with it for a few days and have only landed with myself getting more confused, especially since the `.is` methods aren't exactly documented anywhere.

**Comment by marbuser** [comment]
Something else I want to bring up, the examples provided seem a little light on documentation?
This is the webhook example for your PHP api;
https://github.com/mollie/mollie-api-php/blob/master/examples/payments/webhook.php

Even that single file is incredibly well documented, outlining all methods as well as what they do. Including how to determine if there was a chargeback or refund...

In comparison, the JS example;
https://github.com/mollie/mollie-api-node/blob/3185f03a07b929178013f81432cd3bf41d6b8272/examples/with-express/02-webhook-verification.js

Has minimal documentation, and only outlines 2 methods you can actually use.

Even if we put that aside, you'd assume the methods would be unanimous across all your frameworks, but that's not true either. The JS has maybe half the methods the PHP framework has, which obviously is pretty annoying.

Perhaps I'm wrong, but even by looking at the source code, it seems like these methods are missing.

**Comment by vernondegoede** [comment]
Hi @marbuser 👋 

Sorry for the delayed response. I agree regarding the lacking documentation – we're working on documentation improvements for the Node API client.

> It would seem the ability to distinguish paid transactions, refunds, and disputes all on the same webhook is incredibly complicated? 

The reason we call the same webhook for all state changes is because payments initially become paid, but can be refunded / charged back at a later point ([check out this graph](https://docs.mollie.com/payments/status-changes#how-does-one-status-lead-to-another) for more information). A refunded payment technically is still paid, the money is just returned to the consumer.

> Can't tell if I'm doing anything wrong, but after looking at the code, there is isPaid which I'd assume you'd use to check, well if a payment was paid... However, even on disputes and refunds this is true... So that can lead to duplication of "successful" responses.

I would recommend to do something like this, when handling the webhook:

```js
app.post('/webhook-endpoint-on-my-server', (req, res) => {
    mollieClient.payments
      .get(req.body.id)
      .then(payment => {
        if (payment.isPaid()) {
            // Payment is paid, but can be refunded from API / Dashboard at a later point.
            if (payment.amountRefunded && parseFloat(payment.amountRefunded.value) > 0) {
                // Mark payment as refunded internally. Send email to consumer regarding successful refund.
                return;
            }

            // Payment has become "paid". Mark payment as paid internally and send order confirmation to consumer. Send consumer to order confirmation page when it reaces your `redirectUrl`
            return;
        }

        if (payment.isAuthorized()) {
            // Payment is authorized. send order confirmation to consumer. Send consumer to order confirmation page when it reaces your `redirectUrl`
            return;
        }
        
        if (payment.isFailed() || payment.isExpired() || payment.isCanceled()) {
            // Payment is expired / failed / canceled. Make sure the consumer is sent back to checkout page when it reaches your `redirectUrl`.
            return;
        }
      })
      .catch(error => {
        // Do some proper error handling.
        // It's recommended to still send a 200 OK, see: https://docs.mollie.com/guides/webhooks#how-to-handle-unknown-ids
      });
  });
```

One important thing to note is that you should update the payment status internally as well and check whether the status has actually changed when your webhook gets called. This will prevent multiple order confirmations to be send to a consumer in case the webhook gets called twice.

> Perhaps I'm wrong, but even by looking at the source code, it seems like these methods are missing.

Agreed. I'll create issues to align the methods across different API clients.

**Comment by marbuser** [comment]
Hey @vernondegoede ,

Thanks. I'll give this a try. One final question, when it comes to chargebacks, can I just do the same check as the PHP API?

Which is;
`return !empty($this->_links->chargebacks);`

(Of course I will make it actual JS and such but the same logic.)

Also if that is the case, does this link get generated/added to the transaction as soon as the dispute is opened?

Thanks.

**Comment by vernondegoede** [comment]
Correct @marbuser: the `chargebacks` link will only be exposed within `_links` when the payments actually has been charged back.

Another way to check for chargebacks would be [to embed them](https://docs.mollie.com/reference/v2/payments-api/get-payment#embedding-of-related-resources) when retrieving the payment. This will save you an additional fetch for the actual chargebacks.

```js
app.post('/webhook-endpoint-on-my-server', (req, res) => {
    mollieClient.payments
      .get(req.body.id, {
        embed: 'chargebacks' // <- Please note the `embed` option
      })
      .then(payment => {
        if (payment.isPaid()) {
            // Payment is paid, but can be refunded from API / Dashboard at a later point.
            if (payment.amountRefunded && parseFloat(payment.amountRefunded.value) > 0) {
                // Mark payment as refunded internally. Send email to consumer regarding successful refund.
                return;
            }

            // Payment has become "paid". Mark payment as paid internally and send order confirmation to consumer. Send consumer to order confirmation page when it reaces your `redirectUrl`
            return;
        }

        if (payment.isAuthorized()) {
            // Payment is authorized. send order confirmation to consumer. Send consumer to order confirmation page when it reaces your `redirectUrl`
            return;
        }
        
        if (payment.isFailed() || payment.isExpired() || payment.isCanceled()) {
            // Payment is expired / failed / canceled. Make sure the consumer is sent back to checkout page when it reaches your `redirectUrl`.
            return;
        }
      })
      .catch(error => {
        // Do some proper error handling.
        // It's recommended to still send a 200 OK, see: https://docs.mollie.com/guides/webhooks#how-to-handle-unknown-ids
      });
  });
```

In case of a chargeback, your response will look like this:

```
{
  [...]
  _embedded:
   { chargebacks:
      [
        { resource: 'chargeback',
          id: 'chb_xxx',
          amount: { value: '8.95', currency: 'EUR' },
          createdAt: '2019-05-04T00:00:18+00:00',
          paymentId: 'tr_xxx',
          settlementAmount: { value: '-8.95', currency: 'EUR' },
          _links:
           { self:
              { href: 'https://api.mollie.com/v2/payments/tr_xxx/chargebacks/chb_xxx',
                type: 'application/hal+json' },
             payment:
              { href: 'https://api.mollie.com/v2/payments/tr_xxx',
                type: 'application/hal+json'
              } 
          } 
        } 
      ] 
    } 
};
```

Which you can check using:

```js
const hasChargebacks = payment._embedded && payment._embedded.chargebacks && payment._embedded.chargebacks.length > 0
```

**Comment by marbuser** [comment]
Hey @vernondegoede 

Sorry to comment on this since it's closed, but the solution for chargebacks you provided does not work.

The `embed` option does nothing and results in nothing extra being added to the response.

Additionally, even checking the `_links` doesn't work either as the chargeback link is not added. Perhaps this is a bug in test mode. However, I'm confident it is 100% not working as intended.

I've been debugging it for a couple of hours now and I can see no errors on my end. I even pretty much copy pasted your exact code and it still doesn't work.

Not really sure what to do about this to be honest.
