### ISSUE TITLE
No way to pass count to methods.all

### ISSUE THREAD

**Issue by Ziao** [mollie/mollie-api-node#11]
When calling Mollie.methods.all, you will always get a maximum of 10 results back, without any way to retrieve more. There is no way to pass a count parameter.

```
Base.prototype.all = function(callback) {
      return this.api.callRest("GET", this.constructor.resource, null, null, (function(_this) {
```
^ the data parameter is hardcoded to null

Would be nice to implement this

(See https://www.mollie.com/en/docs/reference/methods/list)

**Comment by willemstuursma** [comment]
I think it'd be good to move away from the default of ten to a higher default, e.g. 20 or 25. @RickWong ?
