### ISSUE TITLE
v3: Various invalid TypeScript definitions

### ISSUE THREAD

**Issue by Karasuni** [mollie/mollie-api-node#122]
Since v3 TypeScript definitions have been added but some are invalid:

```
@mollie\api-client\dist\types\src\models\OrderLine.d.ts

Error:(22, 5) TS2416: Property '_links' in type 'OrderLine' is not assignable to the same property in base type 'IOrderLine'.
  Type '{ productUrl: null; imageUrl: null; }' is not assignable to type 'IOrderLineLinks'.
    Types of property 'productUrl' are incompatible.
      Type 'null' is not assignable to type 'IUrl'.
```

```
@mollie\api-client\dist\types\src\models\Payment.d.ts

Error:(12, 5) TS2416: Property 'id' in type 'Payment' is not assignable to the same property in base type 'IPayment'.
  Type 'null' is not assignable to type 'string'.
(Repeated)
```

```
@mollie\api-client\dist\types\src\resources\customers\payments.d.ts

Error:(53, 5) TS2416: Property 'create' in type 'CustomersPaymentsResource' is not assignable to the same property in base type 'CustomersBaseResource'.
  Type '(params: ICreateParams, cb?: CreateCallback | undefined) => Promise<Payment>' is not assignable to type '(prms: any, cb?: ResourceCallback | undefined) => Promise<Model>'.
    Type 'Promise<Payment>' is not assignable to type 'Promise<Model>'.
(Repeated)
```

Many of these issues are from interface implementations that override a specifically typed value (`string`) with `null` or other invalid typecasting.

**Comment by Pimm** [comment]
Thanks for the bringing this to our attention.

Currently, this library produces a lot of errors when compiled with `strictNullChecks` (or `strict`) turned on. I personally feel this is something that should be fixed.

However, to my knowledge you shouldn't be getting errors like this just using the library. Not even with `strictNullChecks` on. Are you getting these issues while using the library? And if so, could you show us the setup which is giving you these issues?

**Comment by JFGHT** [comment]
Yeah, the `strict: true` is a big problem here.

**Comment by Pimm** [comment]
> Why would the payments `get` method return a `Payment` with all its attributes nulled?

It's because this is a library rewritten in TypeScript but originally designed for/in JavaScript. Fields are set to `null` to make them exist, which is a common pattern in JS but has no place in TS.

If I may ask: does this hinder your own development? This should be fixed, but whether it actively hinders you determines the priority.

**Comment by Karasuni** [comment]
[**@Pimm**](https://github.com/Pimm) commented on [Jan 9, 2020, 3:52 PM GMT+1](https://github.com/mollie/mollie-api-node/issues/122#issuecomment-572596095 "2020-01-09T14:52:37Z - Replied by Github Reply Comments"):
> > Why would the payments `get` method return a `Payment` with all its attributes nulled?
> 
> It's because this is a library rewritten in TypeScript but originally designed for/in JavaScript. Fields are set to `null` to make them exist, which is a common pattern in JS but has no place in TS.
> 
> If I may ask: does this hinder your own development? This should be fixed, but whether it actively hinders you determines the priority.

I've reverted to the previous version because it broke in production. Each of these errors prevented compilation for production as these are configured to not allow any typescript errors.

**Comment by JFGHT** [comment]
@Pimm I just added a few `@ ts-ignore` for now...

**Comment by neelance** [comment]
I just ran into this issue. I think I'll just use plain HTTP requests for now.

**Comment by Pimm** [comment]
Hi Richard and others,

Good news: we are working on this. Thank you for your patience.

**Comment by Brmm** [comment]
Our builds also break and `@ts-ignore` is not working for me.  I found this method to work in my case:

Create a file `sink.d.ts`
```typescript
declare module "@mollie/api-client";
```

Add this to your tsconfig.json
```json
    "baseUrl": ".",
    "paths": {
      "@mollie/api-client": ["./sink.d.ts"]
    }
```

Please fix this, I'd love to use the types!

**Comment by Pimm** [comment]
We just merged a PR which should fix most issues with types, if not all.

I will notify you when a new version is available on NPM.
