### ISSUE TITLE
Functionality request: list payments between dates

### ISSUE THREAD

**Issue by DigitalLeaves** [mollie/mollie-api-node#123]
I have a feature request. I think this is pretty basic stuff. Really amazed Mollie API won't allow this indeed :).

In the endpoint https://api.mollie.com/v2/payments, there should be a way of looking for payments between dates. My proposal is to add two parameters:
- startDate
- endDate

I am integrating many banking solutions/payment gateways with our platform right now and basically all of them allow this. It should not be that hard to add to Mollie I guess, given that is just a database query parameter. 

Use case: accountancy, getting a statement of movements for month X or quarter Y. As it is now, if you want to do this, you need to iterate through the whole list (using pagination) and then filter out the results of certain month and year, which is, as the number of users in the platform grows, certainly unscalable.

**Comment by JorikMollie** [comment]
This is a good suggestion.

I've created a feature request at for our development team to see if we can implement this in the future.

**Comment by vernondegoede** [comment]
I'm closing this issue for now, as this is not related to the Node API Client.

**Comment by DigitalLeaves** [comment]
Good. How can we be notified of changes on its status then. Is there a similar ticket being opened in the API side or any other place please?
