### ISSUE TITLE
Question: Credit a customer 

### ISSUE THREAD

**Issue by kimgysen** [mollie/mollie-api-node#124]
I have the use case where our Q&A website would serve as intermediary between askers and respondents.   
From the documentation it is clear for me how to perform a regular payment (which is what askers would do) or refunds (which I assume is a refund on a prior payment), but it isn't all that clear to me how to just credit a new user (like a respondent who only gets credited for answering questions, but doesn't pay).  

Can this be done with Mollie?

**Comment by Pimm** [comment]
You are correct that a refund essentially reverses or partially reverses a prior payment. If I understand your question correctly, you plan to create a payment in the opposite direction: from your business to the customer.

Mollie is a payment service provider. I am almost certain that "opposite-direction payments" are unfortunately not supported. I will ask someone else to verify this to be sure.

**Comment by kimgysen** [comment]
Yes, the purpose is to be an intermediary party (like a broker, in a way for example Ebay would do it). Thanks for your swift reply and follow-up.
