### ISSUE TITLE
Update payment not supported?

### ISSUE THREAD

**Issue by Christilut** [mollie/mollie-api-node#128]
It says the Payment update() method is not supported in the v2 API, but the v2 API does show this method: https://docs.mollie.com/reference/v2/payments-api/update-payment

Is it just not implemented yet in the nodejs client?

**Comment by Pimm** [comment]
That is correct: it has not been implemented in this library yet.

There are plans to fill up the gaps in this library in the near future.

**Comment by Christilut** [comment]
Okay. I thought I'd give it a go but I ran into some problems.

Got lots of these when I tried running the tests:
```
 FAIL  tests/unit/models/refund.test.ts
  ● Test suite failed to run

    Cannot find module '..' from 'wireMockClient.ts'

    However, Jest was able to find:
        '../../wireMockClient.ts'
```

And I don't see any documentation about contributing so not sure what to do here.

Also you might want to switch from yarn back to npm because I think Facebook kind of abandoned yarn, there's just 1 developer on it now that made yarn v2.

**Comment by lmolema** [comment]
@Christilut did you made any progress on this in the meantime?

**Comment by Christilut** [comment]
I just do a REST call manually for the UPDATE payment:

```ts
export async function sendMollieRest(method: 'PATCH', url: string, data: object) {
  if (env.NODE_ENV !== env.Environments.Test) {
    await Axios({
      method,
      url,
      headers: {
        Authorization: `Bearer ${env.MOLLIE_API_KEY}`
      },
      data
    })
  }
}

```

**Comment by Pimm** [comment]
We have [a PR ready](https://github.com/mollie/mollie-api-node/pull/142). We plan to make a new beta release which includes this endpoint on Monday.

**Comment by lmolema** [comment]
@Christilut thanks!

@Pimm Thats great, I can wait for Monday :)

**Comment by vernondegoede** [comment]
@Christilut @lmolema We just release `3.2.0-beta.1`, which includes this functionality. More information can be found here: https://github.com/mollie/mollie-api-node/releases/tag/v3.2.0-beta.1

Please note that this is a beta. Let us know if you run into any issues!

**Comment by lmolema** [comment]
@vernondegoede Great! I am testing it and so far it works as expected and no issues!
