### ISSUE TITLE
FR: List with parameters

### ISSUE THREAD

**Issue by Christilut** [mollie/mollie-api-node#129]
It would be nice if there is a helper method/overload for the `.list()` functions so that I can do something like this:
```js
await MollieClient.customers.find({
  email: 'test@example.com'
})
```

That would return a list of customers. Paginated like normal.

It should be generic really so that it can accept any property and be able to deep equal as well, eg for `metadata.foo.bar`. Can be applied to all `.list()` methods for every endpoint. I think this would be a really nice addition.

**Comment by vernondegoede** [comment]
Hi @Christilut,

This is now supported in the latest beta: `3.2.0-beta.1`. More information can be found here: https://github.com/mollie/mollie-api-node/releases/tag/v3.2.0-beta.1

Please note that this is a beta, and should be used at your own risk. Let us know if you run into any issues, and we'll be happy to assist.

**Comment by Pimm** [comment]
Vernon was a bit overexcited yesterday. This hasn't been included in the library just yet.

I do, however, think this is at least an interesting idea.

You could use [filter](
https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) today to filter the list in your codebase:
```javascript
const customers = (await mollieClient.customers.all())
  .filter(candidate => 'test@example.com' == candidate.email);
```
(Lists returned by this library are arrays at heart.)

The downsides are that you would have to do pagination yourself, and that you would be loading the entire list over the network and into memory in one go.

I am personally not in favour of something like:
```javascript
{
  email: 'test@example.com'
}
```
You would quickly run into the limitations of that syntax. What if I want to find all refunds with status pending _or_ processing? What if I want to find all payments with an amount _greater than_ €10?

But `mollieClient.customers.filter(candidate => 'test@example.com' == candidate.email)` could be useful. I'll put this up for discussion.
