### ISSUE TITLE
payments.get testmode not working

### ISSUE THREAD

**Issue by rikivesa** [mollie/mollie-api-node#139]
`mollieClient.payments.get("tr_RDxzQqnfzd", {testmode: true}) `

gives

`{ ApiError: Payment tr_RDxzQqnfzd exists, but the wrong mode is used. Try switching live / test API keys.`

but a get to https://api.mollie.com/v2/payments/tr_WDzEAVacaP?testmode=true is working fine.

**Comment by Pimm** [comment]
This should work with the version currently on `master`. It is unfortunately a bug present in the current version on npm.

We will prepare a beta release of a new version, and I will notify you when it is available.

**Comment by jamesjjk** [comment]
@Pimm The same is for the orders API testmode does not work as expected.
```
orders.get(mollieOrderId, {
                testmode,
                embed: [
                    'payments',
                    'refunds',
                    'shipments'
                ]
            })
```
Result:
```
ApiError: Order XXX exists, but the wrong mode is used. Try switching live / test API keys.
```

**Comment by Pimm** [comment]
Could you try this with the latest beta version?

`npm install @mollie/api-client@beta`

**Comment by jamesjjk** [comment]
@Pimm Thanks its resolved with the beta version. However this issue persists: https://github.com/mollie/mollie-api-node/issues/144
