### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by brechtarnou** [mollie/mollie-api-node#141]
Hi all,

How to embed a QR code via express to mollie?

Kind Regards,
Brecht

**Comment by Pimm** [comment]
Hi, Brecht!

Have you had the chance to read the [guide on QR codes](https://docs.mollie.com/guides/qr-codes)?

**Comment by brechtarnou** [comment]
Hi Pimm,

Thanks for that information, didn't know mollie did it automatically when possible.
