### ISSUE TITLE
Resolving the correct profile for a connected account

### ISSUE THREAD

**Issue by jamesjjk** [mollie/mollie-api-node#143]
We would like to understand what the correct procedure is for resolving the profile of the connected account.

- Assume we have a valid client "connected" via connect api
- Assume there are multiple profiles for the client
- We can list and get the relevant profiles

How do we resolve the relevant profile for the connected account so we can list accepted payment "methods for the client.

This is an urgent query, lots of client accounts waiting to connect.

**Comment by vernondegoede** [comment]
You should be able to make a call to the Profile API using the access token of the connected partner.

Please note that this functionality has just been released in `3.2.0-beta.1`: https://github.com/mollie/mollie-api-node/releases/tag/v3.2.0-beta.1

**Comment by jamesjjk** [comment]
@vernondegoede Thanks for the feedback, we noticed the additions. However I think the query is slightly different.
- Consider that a "connect" client can have many profiles.
- How do we know which profile from the "get" profiles for the specific client to use? i.e. which one is authorised correctly?

**Comment by vernondegoede** [comment]
As OAuth2 happens on organization level, there's no way of knowing which profile to use for a client. You should ask your client to set a preferred profile within your application.

You can check out the way we do this in our in-house OAuth2 app useplink.com. When creating a payment, we ask the merchant to select a website profile to create the payment for.

**Comment by jamesjjk** [comment]
Thanks understood, this could be added to the documentation of Mollie. But not relevant to the node library.
