### ISSUE TITLE
Orders.get embedded is returning undefined

### ISSUE THREAD

**Issue by jamesjjk** [mollie/mollie-api-node#144]
Library version 3.2.0-beta.1 (due to testmode bug)

When requesting orders with embeds parameter: 
```
embed: [
                    'payments',
                    'refunds',
                    'shipments'
                ]
```

The order returns _embedded: undefined

**Comment by Pimm** [comment]
Thanks. I'll look into this.

**Comment by Pimm** [comment]
This will be fixed in the next version.

For today ‒ depending on your requirements ‒ perhaps embedding only one resource (payments, or refunds, or shipments) at a time could be a workaround.

**Comment by vernondegoede** [comment]
Release `@mollie/api-client@3.2.0-beta.2`
