### ISSUE TITLE
Cancel order endpoint testmode parameter not accepted

### ISSUE THREAD

**Issue by jamesjjk** [mollie/mollie-api-node#147]
When calling orders.cancel([id], { testmode: true }). it is not accepted by the api there seems to be an issue with calling the delete request with a parameter, it seems it only accepts a form element.

**Comment by Pimm** [comment]
Hi, thanks for creating this issue.

Are you using Mollie Connect/OAuth?
What is the error that you get?

**Comment by jamesjjk** [comment]
@Pimm Correct using Mollie Connect.
As we written our own library to patch some of the problems, I currently do not have the exact error, but in principal it gives an error that the Order exists but the mode is wrong. I believe the testmode parameter is not being sent as a x-form header and encoded parameter but instead as a query parameter.

**Comment by Pimm** [comment]
Could you try this on the new beta version?
`npm install @mollie/api-client@beta`

Regarding the library that you are using in-house: I would very much like to improve this library to the point where there is no more need for a third-party alternative. Would you be open to getting in touch so we can discuss this further?

**Comment by Pimm** [comment]
This should be fixed in the current version of the library. Please create a new issue if you have reason to believe otherwise.
