### ISSUE TITLE
Move to community standards

### ISSUE THREAD

**Issue by StevenLangbroek** [mollie/mollie-api-node#15]
Hey guys,

I had some extra time, and started a rewrite in my fork. Some explanation:
## ES6 over Coffeescript

The JS community at large is moving to ES6 over Coffeescript, mostly because the most useful features of Coffeescript are in ES6 now (classes, static properties, lexically bound arrow functions with implicit return, ).
## Tests

I don't see any tests in the repo, and this worries me. Especially considering alot of stuff is "pure functions", and everything else can have its external dependencies mocked (kudos for that).
## ESLint

Proper ESLint setup (in progress btw, not final yet), can make it almost impossible to introduce a whole range of common bugs (typos in variable names, unused modules, accidental shadowing).

I spent about 30 minutes with it so far, you can see in [`StevenLangbroek:es6`](https://github.com/StevenLangbroek/mollie-api-node/tree/es6). Let me know if this is a direction you want to move in, think I can wrap it up in about 2-3 weeks considering my dayjob (or sooner if you can spare some capacity and feel like it's worth your time ;) ).

**Comment by RickWong** [comment]
Hi Steven, thanks for your valuable feedback on our Node package. 

Internally we have discussed the future of this package as well, and we arrived at the same conclusions as yours regarding the outdated structure, use of deprecated tooling and standards, and the lack of continuous integration. So we definitely share the same ideas about possible improvements.

**Comment by Daanvm** [comment]
Thanks Steven for the rewrite. Someone else did also write an ES6 client for our api: [Geexteam/mollie-ES6](https://github.com/Geexteam/mollie-ES6). Maybe it makes sense to combine the effort instead of creating multiple versions?

I haven't taken a deeper look into those two rewrites so I have no idea which client would be a beter start to work with. In fact, I don't even know if @Geexteam might be interested in this.

**Comment by azachar** [comment]
Also, it would be cool, if you could follow the http://semver.org/spec/v2.0.0.html. Your new features marked as bug fixes are causing me some issues. ( I am creating a bug report ).

Could you also fix a discrepancy in your tags? You said that the latest version is 1.3.2 but in your tags I only see 1.2.x???

Thanks for your considerations.

**Comment by philkunz** [comment]
I recommend TypeScript, as it offers ES7 features, static type checking and excellent IDE intellisense.

**Comment by HofmannZ** [comment]
Any updates on the future of this package?

**Comment by mikaturk** [comment]
@philkunz yup, using typescript right now with async/await for google cloud functions, native js support is coming to Node in October (Node 8 LTS)

**Comment by adriaanmol** [comment]
Wont take long anymore. See pull request: #31

**Comment by dabroek** [comment]
I regret it took this long, yet I am thrilled to announce we just published the updated version of our package under the `mollie-api-node@next` tag. 🎉
