### ISSUE TITLE
Order Lines update does not work?

### ISSUE THREAD

**Issue by patrickw-code** [mollie/mollie-api-node#155]
Hi team,

We are trying to update an order line through the mollieClient, but we are stuck in the error message "ApiError: The order id is invalid". We are using the latest version of the package.

We have checked the data that we want to update, but that data is correct according to the data in the Mollie Dashboard.

This is the call we're doing:

`
    mollieClient.orders_lines.update('odl_xxxxxx', {
      orderId: 'ord_xxxxxx', 
      name: 'Test' 
    })
`

This is the same data as we see in our Dashboard. The order was placed and is currently in the state 'Geautoriseerd' / 'Authorized'.

It seems like a bug, but perhaps we're doing something wrong in the request.

Thanks in advance!

**Comment by Pimm** [comment]
Hi, thanks for bringing this to our attention.

The line of code you posted seems correct. I will try and see whether I can figure out what went wrong.

**Comment by patrickw-code** [comment]
If it helps. It seems that the first argument must be an order since there is a check on the prefix of the first argument. Unfortunately my knowledge in Typescript is not good enough. 

`
if (!lodash.startsWith(id, Order.resourcePrefix)) {
  Resource.createApiError('The order is invalid');
}
`

**Comment by Pimm** [comment]
That code is old. Can you double-check that you are indeed using the latest version of the library (i.e. 3.2.0)?

**Comment by patrickw-code** [comment]
Damn... missed that there was a 3.2.0. This issue has been resolved in version 3.2.0.

Sorry for the inconvenience and thanks!

**Comment by Pimm** [comment]
No inconvenience at all!

You just stumbled upon a bug we "accidentally" fixed in the refactor. That's great!

Good luck on your project.
