### ISSUE TITLE
Error: readFileSync is not a function

### ISSUE THREAD

**Issue by JoppeMeijers** [mollie/mollie-api-node#156]
When I install this API and use the sample code to make a first transaction I get the following error:
Uncaught TypeError: g.a.readFileSync is not a function, and no test transaction will be sent. the environment can be tested via:
[https://picoo-hire-b2c.web.app/](https://picoo-hire-b2c.web.app/) and the error will appear if you press the 'test transactie' button at the bottom of the page. Then the following function is performed:

```
 testPayment(){
       let  mollieClient = createMollieClient({ apiKey: 'test_7K9sDETkbB7ctsJ2TqwyUnkAMf56ur' });
        mollieClient.payments.create({
            amount: {
              value:    '10.00',
              currency: 'EUR'
            },
            description: 'Test of picoo mollie',

  redirectUrl: 'https://yourwebshop.example.org/order/123456',
  webhookUrl:  'https://yourwebshop.example.org/webhook'
          })
            .then(payment => {
              // Forward the customer to the payment.getCheckoutUrl()
              console.log("payment:"+payment);
            })
            .catch(error => {
              // Handle the error
            });
    }

```

Am I doing something wrong or have I missed something?

**Comment by vernondegoede** [comment]
Hi @JoppeMeijers,

It seems that you're using this SDK outside of Node.js, while this library is meant to be used on the backend side only. More information is [available in our README](https://github.com/mollie/mollie-api-node#a-note-on-use-outside-of-nodejs).
