### ISSUE TITLE
Cannot use string in SequenceType

### ISSUE THREAD

**Issue by Pat4561** [mollie/mollie-api-node#175]
I migrated from 3.0.0-beta.1 package to the latest 3.3.0. I am trying to create a first payment for a recurring payment like this:

`let payment = await this.mollieClient.payments.create({
      amount: { value: price, currency: 'EUR' },
      description: ``,
      redirectUrl: ``,
      webhookUrl: ``,
      sequenceType: 'first',
      customerId: customer.id,
    });`

This used to work, but I get the following error:

`Type '"first"' is not assignable to type 'SequenceType'.`

When I compare the versions, I see that the expected type is indeed changed, from null in the beta version to SequenceType. This does not match the documentation online, as it says that I should be able to pass a string.

**Comment by Pimm** [comment]
Hi Patrick!

The documentation on [docs.mollie.com/reference/v2](https://docs.mollie.com/reference/v2) is for the base API; not the Node.js client specifically. You can expect minor inconsistencies like this one.

If you really wanted to, you could turn off type safety for this line. Your code will work. However, the better fix is to use `SequenceType`:
```javascript
import { SequenceType } from '@mollie/api-client';

let payment = await this.mollieClient.payments.create({ amount: { value: price, currency: 'EUR' }, description: ``, redirectUrl: ``, webhookUrl: ``, sequenceType: SequenceType.first, customerId: customer.id, });
```
Or:
```javascript
const { SequenceType } = require('@mollie/api-client');

let payment = await this.mollieClient.payments.create({ amount: { value: price, currency: 'EUR' }, description: ``, redirectUrl: ``, webhookUrl: ``, sequenceType: SequenceType.first, customerId: customer.id, });
```

**Comment by Pat4561** [comment]
Thanks for your response Pimm! I got it working indeed. I copied my code from [this example](https://github.com/mollie/mollie-api-node/blob/be56bf130e9b5960ff9ef6cbb973a10337c3f553/examples/customers/create-payment-with-mandate.js).

But I guess that example is just not updated then.

**Comment by Pimm** [comment]
That example is (plain) JavaScript, the [TypeScript example can be found here](https://github.com/mollie/mollie-api-node/blob/v3.4.0/examples/customers/create-payment-with-mandate.ts).

Maybe that is something we can make more evident.

**Comment by Pat4561** [comment]
Ofcourse, now I see it. I had not noticed this was plain Javascript. Thanks for your help.
