### ISSUE TITLE
Full Support for Chargebacks

### ISSUE THREAD

**Issue by maknotavailable** [mollie/mollie-api-node#209]
Is there any plan to fully support chargebacks in the node wrapper?

From the API documentation, there should be a method for the payment object to get 'amountChargedBack' -> https://docs.mollie.com/reference/v2/payments-api/get-payment#response 

Thanks in advance!

**Comment by Pimm** [comment]
Thanks for the ticket.

The answer is **yes**. The goal of this library is to support the Mollie API in full.

I'll look into this, and keep you up-to-date.

**Comment by Pimm** [comment]
`amountChargedBack` has been added, and you can use it today by installing the _beta_ tag: `npm install @mollie/api-client@beta`. Should you have any issues with the beta version, please let us know.
