### ISSUE TITLE
Return type createMollieClient

### ISSUE THREAD

**Issue by woutervanbakel** [mollie/mollie-api-node#210]
I'm experimenting with the Mollie node api from Typescript. Any reason to not give this function
https://github.com/mollie/mollie-api-node/blob/8b6d05e871a50bbadabd937cf8630daa5d9e6194/src/createMollieClient.ts#L36
A return type I could import and use from typescript? 

This is what I'm trying to do:
```
client(): any {
    return createMollieClient({ apiKey: 'apiKey' });
 }

  createPayment(): Promise<JSON> {
    return this.client().payments.create({});
  }
```
Resulting in a linter warning unsafe call of ```any``` value on this.client()

This I can't do  as the PaymentsResource is not exported
```
client(): {payments: PaymentsResource} {
    return createMollieClient({ apiKey: 'apiKey' });
 }
```

Ideally I would like to do
```
import {MollieClient} from '@mollie/api-client';
client(): MollieClient {
    return createMollieClient({ apiKey: 'apiKey' });
 }
```

**Comment by woutervanbakel** [comment]
A found a old attempt to define a interface https://github.com/mollie/mollie-api-node/blob/typescript-declaration-files/src/create-mollie-api.ts

**Comment by woutervanbakel** [comment]
Found it already https://github.com/mollie/mollie-api-node/blob/8b6d05e871a50bbadabd937cf8630daa5d9e6194/src/types.ts#L5

**Comment by Pimm** [comment]
Thank you, Wouter.

To anyone who wonders here with the same question, you can import `MollieClient` like so:
```typescript
import createMollieClient, { MollieClient } from '@mollie/api-client';

const mollieClient: MollieClient = createMollieClient({ apiKey: 'test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM' });
```
(Although in a lot of cases you won't have to, as TypeScript can often infer the type.)

**Comment by Pimm** [comment]
Thank you, Wouter.

To anyone who wanders here with the same question, you can import `MollieClient` like so:
```typescript
import createMollieClient, { MollieClient } from '@mollie/api-client';

const mollieClient: MollieClient = createMollieClient({ apiKey: 'test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM' });
```
(Although in a lot of cases you won't have to, as TypeScript can often infer the type.)
