### ISSUE TITLE
Incorrect typring for client.customers_subscriptions.create

### ISSUE THREAD

**Issue by robindijkhof** [mollie/mollie-api-node#227]
According to the docs, `startDate` is optional. In TypeScript I get an error saying `startDate` is required.

Example code:

    await client.customers_subscriptions.create({
        amount: {currency: "EUR", value: "3.00"},
        customerId: payment.customerId!,
        interval: "3 months",
        description: "Quarterly payment",
        webhookUrl: "thatshouldbethis"
      });

Error:

TS2345: Argument of type '{ amount: { currency: string; value: string; }; customerId: string; interval: string; description: string; webhookUrl: string; }' is not assignable to parameter of type 'CreateParameters'.   Property 'startDate' is missing in type '{ amount: { currency: string; value: string; }; customerId: string; interval: string; description: string; webhookUrl: string; }' but required in type 'Pick<SubscriptionData, "amount" | "description" | "mandateId" | "interval" | "startDate">'.  data.d.ts(51, 5): 'startDate' is declared here.

Adding `startDate` fixes the problem.

**Comment by Pimm** [comment]
Thanks for opening the issue.

`startDate` should indeed be optional[[doc]](https://docs.mollie.com/reference/v2/subscriptions-api/create-subscription#parameters). I shall fix this.

Until the next version is released, you can circumvent TypeScript's check. If you need help with that, please let me know.

**Comment by Pimm** [comment]
`startDate` is optional in the version currently on the _beta_ tag: `npm install @mollie/api-client@beta`. Should you have any issues with the beta version, please let us know.
