### ISSUE TITLE
Add businessCategory to Profile type

### ISSUE THREAD

**Issue by tasoskakour** [mollie/mollie-api-node#242]
According to this DOC https://docs.mollie.com/reference/v2/profiles-api/get-profile `categoryCode` is going to be deprecated in 2022 and `businessCategory` should be used. 

Right now the `Profile` type does not include a `businessCategory` property.

**Comment by Pimm** [comment]
The business category has been added, and you can use it today by installing the _beta_ tag: `npm install @mollie/api-client@beta`. Should you have any issues with the beta version, please let us know.
