### ISSUE TITLE
Mollie API client is integrated into a website or app error

### ISSUE THREAD

**Issue by paulijmker** [mollie/mollie-api-node#243]
I'm working on making a WordPress block in combination with Mollie payment. Now I did an import:

`import createMollieClient from '@mollie/api-client';`

In my console I get the error:

Uncaught Error: Unexpected process release name undefined. This may indicate that the Mollie API client is integrated into a website or app. This is not recommended, please see https://github.com/mollie/mollie-api-node/#a-note-on-use-outside-of-nodejs. If this is a mistake, please let us know: https://github.com/mollie/mollie-api-node/issues

How can I apply this in my npm package without this error?

**Comment by paulijmker** [comment]
For now I have found a workaround / solution by using the Render Callback with PHP.

**Comment by Pimm** [comment]
Hi @paulijmker!

This library is designed to run on a server.

In a typical setup, the client app ‒ in your case: your website ‒ makes a request to your server, which in turn communicates with Mollie. If you are building something on top of WordPress, you already have a PHP server in place. Therefore it might be more sensible to use the [PHP client](https://github.com/mollie/mollie-api-php) than this one.

If you need more assistance or have any further questions, feel free to comment on this issue. I can also get you in touch with the support team.
