### ISSUE TITLE
fs.readFileSync is not a function

### ISSUE THREAD

**Issue by joeydebreuk** [mollie/mollie-api-node#25]
Hi Guys,

I am building an reactjs app and I am planning to use Mollie using this rep but something goes wrong with using the fs functions in the code of mollie-api-node.

Im getting the following error:

Uncaught TypeError: fs.readFileSync is not a function
    at Client.module.exports.Client.callRest (bundle.js:69617)
    at Payments.module.exports.Base.create (bundle.js:75793)
    at Object.<anonymous> (bundle.js:10888)
    at __webpack_require__ (bundle.js:556)
    at fn (bundle.js:87)
    at Object.<anonymous> (bundle.js:591)
    at __webpack_require__ (bundle.js:556)
    at bundle.js:579
    at bundle.js:582

using the following code:

```
var Mollie = require("mollie-api-node");
var mollie = new Mollie.API.Client;
mollie.setApiKey("test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM");

mollie.payments.create({
    amount:      10.00,
    description: "My first API payment",
    redirectUrl: "https://webshop.example.org/order/12345/",
    webhookUrl:  "https://webshop.example.org/mollie-webhook/"
}, function (payment) {
    mollie.response.writeHead(302, { Location: payment.getPaymentUrl() })
});
```

Is there anyone with a similar problem? 

Thanks!

**Comment by dabroek** [comment]
This is a webpack issue. Add the following to your webpack config file:
```json
node: {
  fs: 'empty'
}
```

**Comment by TimDeSmet** [comment]
I've encountered this issue as well:

![image](https://user-images.githubusercontent.com/10990038/80525441-856d0880-8991-11ea-83c2-8c0a2f6ec32a.png)

Currently I'm building a React app (starting from the create-react-app toolchain).

Unfortunately this setup does not allow for an easy customization of webpack... 
Does anybody know any way around this? Without rewiring the full app? 

Thanks!
