### ISSUE TITLE
implement in NextJS

### ISSUE THREAD

**Issue by Rickkorsten** [mollie/mollie-api-node#252]
Is it possible to integrate the client in NextJS as an api route?

**Comment by Pimm** [comment]
This is possible, yes. See [nextjs.org/docs/api-routes/introduction](https://nextjs.org/docs/api-routes/introduction).

You will likely put your Mollie API key in [an environment variable](https://nextjs.org/docs/basic-features/environment-variables). Please make sure you do not accidentally expose your API key to the client (or _to the browser_, as the Next.js documentation puts it).

Let us know if you run into any issues!

**Comment by Rickkorsten** [comment]
Thx Pim, 
 
So i have filled in everything on the webdashboard to get my account approved. But still i get the response : `'ApiError: Your account is currently suspended' ` 

and 


  ```
title: 'Unprocessable Entity',
  status: 422,
  field: undefined,
  links: {
    documentation: {
      href: 'https://docs.mollie.com/overview/handling-errors',
      type: 'text/html'
    }
  }
}
```

**Comment by Pimm** [comment]
Please [contact support](https://www.mollie.com/en/contact/merchants).
