### ISSUE TITLE
Add support for Enable payment method

### ISSUE THREAD

**Issue by RobbeCl** [mollie/mollie-api-node#253]
Hi!

Is there a possibility to add support for the endpoint enable payment method (https://docs.mollie.com/reference/v2/profiles-api/enable-method).

Thanks!

**Comment by Pimm** [comment]
Thanks for the ticket.

And: **yes**. The goal of this library is to support the Mollie API in full.

**Comment by RobbeCl** [comment]
Okay awesome, thanks for the reply @Pimm!
