### ISSUE TITLE
This API only accepts application/json or application/x-www-form-urlencoded or multipart/form-data as content-type

### ISSUE THREAD

**Issue by sjorsvanheuveln** [mollie/mollie-api-node#255]
Since 6 days ago my site is throwing this error when starting a mollie payment. I haven't changed anything since a couple of months. Any idea what's going on here?

```
{ error: 
   { type: 'request',
     message: 'This API only accepts application/json or application/x-www-form-urlencoded or multipart/form-data as content-type.',
     links: { documentation: 'https://docs.mollie.com/' } } }
```

Using mollie-api-node": "^2.0.0-alpha.1

**Comment by sjorsvanheuveln** [comment]
I upgraded to the latest client, so I solved the issue for myself. But very weird this got broken, this must have been through an update at Mollie's side. I wonder whether I'm the only one where the implementation was broken.

**Comment by Pimm** [comment]
Thanks for reporting back!

It looks like this only affects the pre-release of 2.0.0, as [it used an odd `Content-Type`](https://github.com/mollie/mollie-api-node/blob/v2.0.0-rc.1/src/create-http-client.js#L21).

For anyone else who finds themselves with this issue:
Please upgrade to 2.3.2 if you are on Node.js 6+, or 2.1.2 if you are on an older Node.js. If you have a few more minutes to spare, consider upgrading to the latest version. There are very few breaking changes, migrating shouldn't take too much effort.
