### ISSUE TITLE
Please add PaymentLink to types.d.ts

### ISSUE THREAD

**Issue by JohanManders** [mollie/mollie-api-node#264]
Because I have to switch from the Payment API to the Payment Link API, I came across this little annoyance.

For importing Payment I can use:

```ts
import { Payment as MolliePayment } from '@mollie/api-client'
```

So when I switched to Payment Link, I thought I could use:

```ts
import { PaymentLink as MolliePaymentLink } from '@mollie/api-client'
```

But this does not work, because the file ```@mollie\api-client\dist\types\types.d.ts``` does not have this line:

```ts
export { default as PaymentLink } from './data/paymentLink/PaymentLink';
```

Could you please add it, this would make PaymentLink work similar like Payment.

Thanks!

PS It would be great if I could use ```expiresAt``` with the regular Payment API, so that I did not have to switch to the Link version of the API.

**Comment by Pimm** [comment]
Thanks Johan,

I'll export `PaymentLink`!

Could you elaborate on how you would use `expiresAt` for payments?

**Comment by JohanManders** [comment]
Hi Pimm,

I have a case where we want to sell some tickets between ```14:00``` and ```15:00``` and a raffle will be held at ```15:30```, 30 minutes after the last moment someone can buy a ticket.

But, payment methods have different expire times. I am sure that no iDeal payment will come through after ```15:15```, because the expire time is 15 minutes, but for example Credit card (30 minutes) or Paypal (3 hours) can come through (way) after the raffle is done.

We have to inform these people that they paid for something that they did not participate in the raffle and have to pay them back. This is extra hassle...

Payment Link API has a ```expiresAt``` field that helps a bit. The payment link is not valid after this set datetime, but people could open the link, get some beer while leaving their browser tab open and still pay after an hour if they use Paypal for instance.

A solution for the Payment API would be to loop through all pending orders at ```15:15``` and cancel them all, but yeah... it is a bit of a hacky solution in my opinion.

So, I would love to 'say' to Mollie that a payment cannot be done after a certain datetime. That the payment ```expiresAt```, even if someone leaves his browser tab open at a certain Mollie payment page/ link.

**Comment by janpaepke** [comment]
@Pimm please advise how we plan to continue here.

**Comment by Pimm** [comment]
The question about `expiresAt` has been flying under the radar, because it's buried in this ticket about `PaymentLink`. It would be great if we can get closure from the Mollie API team about this.

**Comment by fjbender** [comment]
`expiresAt` on the Payments API will certainly not work due to payments on third party sites as explained above. Introducing something like auto refunds for these payments feels like too much magic... But if I'm missing a significant use case here, I'd recommend adding it to the Feature Request section on [The Discord](https://discord.gg/mollie).
