### ISSUE TITLE
get Methods based on country not working?[BUG]

### ISSUE THREAD

**Issue by DennisSpek** [mollie/mollie-api-node#274]
I tried filtering out payment methods based on the billingCountry parameter but this does not work. Not sure if this is working as intended or an actual bug.

`mollieClient.methods.all({
        includeWallets: 'applepay',
        billingCountry: 'US',
        locale: 'en_US',
        amount: {
          value: '100.00',
          currency: 'EUR',
        },
      })`

Will still show iDeal as an valid payment method. This same issue arises when using the actual API Endpoint.

**Comment by Pimm** [comment]
This might be the intended behaviour. [According to the documentation](https://github.com/mollie/mollie-api-node/blob/v3.6.0/src/binders/methods/parameters.ts#L78), `billingCountry` "_can be used to check whether your customer is eligible for certain payment methods_". iDEAL is "less appropriate" for the US, but I don't think this parameter was designed to filter by whether a method is appropriate. Setting it to `'NL'` doesn't filter out Belfius Pay Button, for instance, even though it's not common in the Netherlands.

As you mentioned, this is not specific to the Node.js client, and therefore above my paygrade. I'll ask around among the Mollians.
