### ISSUE TITLE
Not getting Id from webhook

### ISSUE THREAD

**Issue by SamEchten** [mollie/mollie-api-node#275]
Hello,

When I try to retrieve the id from my webhook route I am not able to get the Id from anywhere, the body of my request is totally empty. I am using NodeJS express. Does anyone have any idea on how to fix this?

The router ->
![router](https://user-images.githubusercontent.com/56364108/170361116-4b197ff2-6f7b-4b95-951b-899f5c059edc.PNG)
The controller ->
![req body id](https://user-images.githubusercontent.com/56364108/170361118-de5495b5-593c-4f49-a011-d1208e57c9a5.PNG)
The body / request ->
![body](https://user-images.githubusercontent.com/56364108/170361119-38d02c05-4424-41cc-a3ae-ad469f47875b.PNG)

**Comment by Pimm** [comment]
The body of the request doesn't seem empty; it seems to be an empty object (`{}`). My initial instinct says that you might have some middleware in there which attempts to parse the raw body of the request as JSON, which it isn't. [It is URL encoded](https://docs.mollie.com/overview/webhooks).

Please make sure [you have the correct body parsing middleware in place](https://expressjs.com/en/resources/middleware/body-parser.html). If you feel like you have the correct middleware wired up, please share a complete example, including all of the Express-related code as well as the version of Express you're using.

**Comment by SamEchten** [comment]
It was indeed my body parsing middleware that was the problem, I now used express.urlencoded(), this fixed the issue. Thanks for the reply!
