### ISSUE TITLE
Apple Pay button while not specified in `method`

### ISSUE THREAD

**Issue by wezooyuri** [mollie/mollie-api-node#289]
I came across an issue (or lack of documentation) related to the Apple Pay button shown in the Mollie payment interface while using this package.

We create payments with a `method` specified, like

```typescript
const molliePayment = await this.mollieClient.payments.create({
  method: [PaymentMethod.ideal, PaymentMethod.creditcard],
  ...
});
```

When we added the `creditcard` method to this list, the Apple Pay button was also enabled on iOS devices in the Mollie payment view:

<img width="412" alt="Screenshot 2022-08-15 at 08 23 38" src="https://user-images.githubusercontent.com/100122142/184586639-f782f4ed-698c-4c33-b475-cda7ad093861.png">

Altough the flow works fine, we would like to specify explicitly which payment methods are used. Is this behaviour intentional? I would expect Apple Pay to only be included when `PaymentMethod.applepay` is included in the `method` list.

Edit - some additional info: the Mollie dashboard also lists payments as a Creditcard payment, but with a Maestro and Apple Pay "label":
<img width="690" alt="Screenshot 2022-08-15 at 08 28 42" src="https://user-images.githubusercontent.com/100122142/184587147-429ed26f-13f9-4fdc-b1fe-8fb8fb12a99c.png">

**Comment by wezooyuri** [comment]
Could very well be that this is unrelated to the node package and should be forwarded to the core Mollie team, if so let me know and I'll open a ticket with them 👍 .

**Comment by Pimm** [comment]
Thanks, Yuri,

This is indeed outside the scope of the Node.js client, and thus [a question for support](//www.mollie.com/contact/merchants).

Tell them I said "hi", and have a great week.
