### ISSUE TITLE
How to test Chargeback in test mode

### ISSUE THREAD

**Issue by FahadTanveerY** [mollie/mollie-api-node#290]
Hi. I just wan’t to ask what is the way to test chargeback in development. Since in the mollie dashboard it says chargeback cannot be tested in test mode. I have tried both v1 as well as v2 apis but unable to find a way to test my implementation.
https://docs.mollie.com/overview/testing
In this documentation it is said that changePaymentState allows us to create refund and chargeback but when I tested that it only shows refund option but nothing for chargedback

**Comment by Pimm** [comment]
To my knowledge, you are correct: chargebacks don't work in test mode.

You can [ask support](//www.mollie.com/contact/merchants) to make sure.
