### ISSUE TITLE
Refund not working in Test mode

### ISSUE THREAD

**Issue by guy-leerman** [mollie/mollie-api-node#296]
When I try to make a refund in Test mode I get the following error

{"status":404,"title":"Not Found","detail":"Payment tr_Zukrw4rcwH exists, but the wrong mode is used. Try switching live / test API 
keys.","_links":{"documentation":{"href":"https://docs.mollie.com/overview/handling-errors","type":"text/html"}}}

**Comment by Pimm** [comment]
It sounds like you are trying to create a test refund for a _live_ payment. You can only create test refunds for _test_ payments.

Are you currently using an API key or an access token?

**Comment by guy-leerman** [comment]
Dear Pimm,
My mistake. Thank you for your quick reply.
Kind regards,
Guy
