### ISSUE TITLE
Enable/disable payment methods

### ISSUE THREAD

**Issue by lucienbl** [mollie/mollie-api-node#310]
Hello,

Sorry if this is a dumb question, but I can't figure out where/how I can enable or disable a payment method with this API wrapper. Is this possible ?

Thanks in advance.

Best regards,
Lucien

**Comment by Pimm** [comment]
Hi Lucien!

It is possible, like so:
```typescript
await mollieClient.profileMethods.enable({ profileId: 'pfl_v9hTwCvYqw', id: 'ideal' })
```

The catch is, `profileMethods` is only available starting with version 3.7.0 of the library, which is currently in beta. You can use it today by installing the _beta_ tag: `npm install @mollie/api-client@beta`.
