### ISSUE TITLE
Return separate "err" and "payment" arguments

### ISSUE THREAD

**Issue by bert-w** [mollie/mollie-api-node#32]
See this snippet from the readme:
```
mollie.payments.create({
    amount:      10.00,
    description: "My first API payment",
    redirectUrl: "https://webshop.example.org/order/12345/",
    webhookUrl:  "https://webshop.example.org/mollie-webhook/"
}, function (payment) {
    response.writeHead(302, { Location: payment.getPaymentUrl() })
});
```

It would be nice if the callback function received
```
function(err, payment) {
  ...
}
```

So that the error is not the same variable. Currently im checking whether the first argument has a `getPaymentUrl()` function, and if it does, i know the payment creation succeeded. Suboptimal though

**Comment by dabroek** [comment]
@bert-w We are in the process of rewriting our node client (see the [v2 branch](https://github.com/mollie/mollie-api-node/tree/v2)). In the new release we will support both promises as the standard `(err, result)` callback.
