### ISSUE TITLE
Webpack <5 error with NG 15

### ISSUE THREAD

**Issue by PatrickRitskes-IG** [mollie/mollie-api-node#320]
Hey Everyone,

When I want to add the Mollie API to my Angular 15 app, and serve it, I get the following compile errors:

Compiled with problems:X

ERROR in ./node_modules/@mollie/api-client/dist/mollie.esm.js 1:0-26

Module not found: Error: Can't resolve 'https' in 'C:\webdev\giant-frontend\node_modules\@mollie\api-client\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
	- install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "https": false }

ERROR in ./node_modules/@mollie/api-client/dist/mollie.esm.js 3:0-40

Module not found: Error: Can't resolve 'querystring' in 'C:\webdev\giant-frontend\node_modules\@mollie\api-client\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "querystring": require.resolve("querystring-es3") }'
	- install 'querystring-es3'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "querystring": false }

ERROR in ./node_modules/@mollie/api-client/dist/mollie.esm.js 4:0-31

Module not found: Error: Can't resolve 'util' in 'C:\webdev\giant-frontend\node_modules\@mollie\api-client\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }

ERROR in ./node_modules/@mollie/api-client/dist/mollie.esm.js 5:0-26

Module not found: Error: Can't resolve 'url' in 'C:\webdev\giant-frontend\node_modules\@mollie\api-client\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
	- install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "url": false }

Want can I do about it?

**Comment by Pimm** [comment]
This client is designed to be used server-side, just like the PHP, Ruby, and Python clients. There should be no direct correction between your client-side application and Mollie.

If you wish to initiate a payment from the client-side application, you should make some kind of request (HTTP or something else) to your server, which in turn connects to Mollie using one of the Mollie client to create the payment. Please see [this description by Florian](//github.com/mollie/mollie-api-node/issues/345#issuecomment-2076479968).
