### ISSUE TITLE
Order dashboard link missing in type definition

### ISSUE THREAD

**Issue by spee** [mollie/mollie-api-node#336]
The `OrderLinks` interface is missing the `dashboard` link, which is returned by the API.

**Comment by janpaepke** [comment]
This is also true for PaymentLinks, which also contains a dashboard URL.

Both should be accessed using `.getDashboardUrl()`, i.e. `order.getDashboardUrl()`

Docs:

- https://docs.mollie.com/reference/get-payment
- https://docs.mollie.com/reference/get-order
