### ISSUE TITLE
Delete mandate response

### ISSUE THREAD

**Issue by ndijkstra** [mollie/mollie-api-node#34]
If merchant deletes Mandates, the API delivers an empty message (HTTP 204). This creates a failure in Node.js, because it expects an answer in JSON (JSON.parse(response).

**Comment by dabroek** [comment]
For people that run into this problem you can use the `@next` flag to get the latest, rewritten version of the library. This version should not contain this error anymore.

**Comment by vernondegoede** [comment]
We just released v2 of our official Node API client, which fixes this error.

To install:

```bash
yarn add @mollie/api-client
```

Check out our [migration guide](https://github.com/mollie/mollie-api-node/blob/v2.0.0/MIGRATION.md) for a complete overview of the changes.
