### ISSUE TITLE
Disabling automatic bank transfer email

### ISSUE THREAD

**Issue by zugende** [mollie/mollie-api-node#342]
**Current behavior:**
When creating a mollie payment `await mollieClient.payments.create({...})` and the only payment method provided is `PaymentMethod.banktranser` an automatic bank transfer email is send to the customer. The documentation states that I can control this email using the `billingEmail` field. Even when setting the billingEmail to **undefined** or **null** the email will be send to the customer.

**Expected beahvior:**
When setting the billingEmail to null no automatic bank transfer email will be send.

**Current workaround:**
I set the billingEmail to an email owned by me. I get all the emails now. But this gets messy really fast.

Can someone point me in a direction to solve this issue? Maybe I am overlooking something.

Thanks so much
Basti

**Comment by fjbender** [comment]
Thanks for raising this issue! It is not, however, something we can change in the node client, as this connects to Mollie platform behavior. Typically, we recommend setting the `billingEmail` to a `/dev/null` type of address to achieve the outcome you describe, similar to what you're currently doing as a workaround.

I'd like to invite you to our [Developer Discord](https://discord.gg/mollie) to raise a feature request for this :)
