### ISSUE TITLE
Test mode

### ISSUE THREAD

**Issue by NicolaiSchmid** [mollie/mollie-api-node#35]
Is there a way to set this SDK into a test-mode for unit- and integration testing. So that no requests at all get sent to your API and responses are mocked?
I don't want to clutter up my Test-mode Interface on https://mollie.com/dashboard.
Or can I obtain more than one Debug API Key?
Thanks for your help!

**Comment by dabroek** [comment]
There is no way to put this package in test mode for the moment. However you can obtain a new test token by resetting your test API key in the dashboard. Do note that this will still "clutter up" your dashboard in test-mode. But do not despair, these test payments will automatically be removed after a week or two. Happy testing!
