### ISSUE TITLE
Please update the payment methods

### ISSUE THREAD

**Issue by nickdevnl** [mollie/mollie-api-node#357]
Some payment methods have been removed and some payment methods have been added to mollie, maybe its time to update it and add all new payment methods and remove old ones.(Giropay and sofort is no longer available.)

**Comment by janpaepke** [comment]
Thanks for bringing this to our attention.
Indeed there seem to be some discrepancies.

Unfortunately the API docs are not consistent on this.

In https://docs.mollie.com/reference/get-payment it lists as possible `method` return values:
```
alma applepay bacs bancomatpay bancontact banktransfer belfius blik creditcard directdebit eps giftcard ideal kbc mybank paypal paysafecard przelewy24 satispay trustly twint
```

Where as in https://docs.mollie.com/reference/get-method it lists as possible `id` return values:
```
alma applepay bacs bancomatpay bancontact banktransfer belfius billie blik creditcard directdebit eps giftcard ideal in3 kbc klarna klarnapaylater klarnapaynow klarnasliceit mybank paypal paysafecard przelewy24 riverty satispay trustly twint voucher
```

@fjbender could you look into this and provide a definitive list? The docs should then also be updated accordingly.

**Comment by fjbender** [comment]
Thanks for pointing this out! The definitive list of all methods supported is the one on the Get Method endpoint. The list on the Get Payment endpoint is technically wrong, as it excludes all methods for which payments can (currently) only be implicitly created through the Create Order endpoint. 

We will fix this in the docs to differentiate correctly between Create Payment and Get Payment.

**Comment by janpaepke** [comment]
All right, we will address this for 4.1.0 using the list from get method:
```
alma applepay bacs bancomatpay bancontact banktransfer belfius billie blik creditcard directdebit eps giftcard ideal in3 kbc klarna klarnapaylater klarnapaynow klarnasliceit mybank paypal paysafecard przelewy24 riverty satispay trustly twint voucher
```
