### ISSUE TITLE
API Docs Issue

### ISSUE THREAD

**Issue by thebillkidy** [mollie/mollie-api-node#36]
Graag meld ik even dat terwijl ik bezig was met de mollie node api dat ik volgende bug tegenkwam:

- API: https://www.mollie.com/nl/docs/reference/mandates/list
- Source file: https://github.com/mollie/mollie-api-node/blob/91cfef5f88c24f8383c9cb93866e8762ea0849a8/src/lib/mollie/api/resource/base.coffee lijn 95

In de docs staat dat de mandaten in een .data key gaan zitten als array. Echter zegt de lijn: 
`list.push(this.copy(body.data[item], new this.constructor.object));`

Wat dus wilt zeggen dat het dit gewoon gaat toevoegen aan het object.

Als ik dit confirmeer met de API call aan te roepen zie ik inderdaad volgend object terugkomen:
`{"0":{"resource":"mandate","id":"mdt_8CWh4RvBGK","status":"valid","method":"directdebit","customerId":"cst_B7759emggz","details":{"consumerName":"T. TEST","consumerAccount":"BE62510007547061","consumerBic":"GEBABEBB"},"createdDatetime":"2017-08-30T08:32:00.0Z"},"totalCount":1,"offset":0,"length":1}`

**Comment by jookes** [comment]
De API response vanaf de mollie API geeft de 'data' in een data key. Deze library zet de data key om in een 'list' (een mollie implementatie van een array). 

Je kan vanaf node over de mandates heen loopen alsof het een array is. De extra keys (offset/totalCount/etc) worden dan genegeerd. 

De documentatie klopt wat dat betreft wel, aangezien ze de 'ruwe' API response tonen. In het geval van deze library krijg je in het mandates object 'gewoon' een array met wat extra velden die je kan benaderen.
