### ISSUE TITLE
Unable to set count on payments.all

### ISSUE THREAD

**Issue by woutersm** [mollie/mollie-api-node#37]
Hi there,

I'm unable to change the count param on the payments.all, whatever I do I always get back a maximum of 10 payments. 

```
mollie.payments.all((payments) => {
  console.log(payments);
}, {count: 20});
```

According to this api doc, I should be able to set it, any idea why it isn't working?

**Comment by dabroek** [comment]
Hi Wouter,

This functionality is available in our `next` branch. You can install this package using `npm install mollie-api-node@next`. Hope that helps!

**Comment by vernondegoede** [comment]
We just released v2 of our official Node API client, which comes with improved pagination and multicurrency support.

To install:

```bash
yarn add @mollie/api-client
```

Check out our [migration guide](https://github.com/mollie/mollie-api-node/blob/v2.0.0/MIGRATION.md) for a complete overview of the changes.
