### ISSUE TITLE
Support for creating terminal payments

### ISSUE THREAD

**Issue by Jakub-Niznik** [mollie/mollie-api-node#378]
In current state there is no support for creating terminal payments.

In type `CreateParameters` param `terminalId` is missing and also in enum `PaymentMethod` method `pointofsale` is missing.

**Comment by janpaepke** [comment]
This is already in preparation (see here https://github.com/mollie/mollie-api-node/pull/347 and here https://github.com/mollie/mollie-api-node/pull/329)

It will be part of the 4.2.0 release, although there is currently no timeline as to when this will be released.

**Comment by janpaepke** [comment]
Closing this issue, since terminal api is being discussed here https://github.com/mollie/mollie-api-node/issues/328
