### ISSUE TITLE
ReactJS Example

### ISSUE THREAD

**Issue by sjorsvanheuveln** [mollie/mollie-api-node#38]
Hi there, 

I'm already a customer of yours for another website of mine using the PHP implementation. I'm currently working on a ReactJS project and want to implement a payment service soon. Do you perhaps by any chance have a ReactJS /ES6 implementation example to implement this? Thanks

**Comment by vernondegoede** [comment]
The ES6 version can be found in the `@next` branch.

**Comment by dabroek** [comment]
@sjorsvanheuveln Only if you would run a server side rendered React application you could use this package on the server side.
