### ISSUE TITLE
Small issue in API docs regarding split payments

### ISSUE THREAD

**Issue by janpaepke** [mollie/mollie-api-node#384]
In [the docs for](https://docs.mollie.com/reference/create-payment) the `routing` parameter in create-payment, there is a tiny mistake.

The child properties contain `releaseDate`, which is described as:
> Optionally, schedule this portion of the payment to be transferred to its destination on a later date. The date must be given in YYYY-MM-DD format.
>
>If no date is given, the funds become available to the connected merchant as soon as the payment succeeds.

This clearly indicates that this is an optional parameter.
However the type is documented as `string`, when it should be `string | null` as is the case for all other optional params.

**Comment by fjbender** [comment]
Fixed and deployed.
