### ISSUE TITLE
Can't resolve 'fs'

### ISSUE THREAD

**Issue by sjorsvanheuveln** [mollie/mollie-api-node#39]
I'm getting hit with this error! Any solutions?

ERROR in ./~/mollie-api-node/lib/mollie/api/client.js
Module not found: Error: Can't resolve 'fs' in 'myproject/node_modules/mollie-api-node/lib/mollie/api'
 @ ./~/mollie-api-node/lib/mollie/api/client.js 39:7-20
 @ ./~/mollie-api-node/lib/mollie.js

**Comment by dabroek** [comment]
I guess you are trying to run this package on the client side. This is e Node.js package and can therefore only be used on the server side.
