### ISSUE TITLE
Testing Mollie

### ISSUE THREAD

**Issue by d46** [mollie/mollie-api-node#392]
Is it possible to test the Mollie library? Stripe provides test card tokens, allowing us to simulate user scenarios with predefined tokens without requiring UI interactions. This functionality is crucial for automated testing. Does Mollie offer similar support?

**Comment by fjbender** [comment]
Unfortunately, we don't yet offer end-to-end testing without user interactions. Typically we recommend setting up automated frontend-based tests with e.g. Cypress. You can find Cypress actions for our sandbox page here: https://github.com/boxblinkracer/cypress-mollie

**Comment by fjbender** [comment]
Yup, you'll just have to `sleep` a lot to prevent odd race conditions and keep your tests stable:

https://github.com/mollie/Shopware6/blob/030266f2e23820d09fda157a005e14e97be7486a/tests/Cypress/cypress/support/actions/storefront/checkout/PaymentAction.js#L83-L127
