### ISSUE TITLE
Create Payment Manually With Exsting Card,Not Subscription Service

### ISSUE THREAD

**Issue by hooooooouzx** [mollie/mollie-api-node#394]
Hello,

I want to store customers' `mandateId` on my website and let them pay more convenient in future payments.But it's not a subscription service.

I posted an [issue](https://github.com/mollie/mollie-api-node/issues/393) yesterday and you reply me,thanks very much.But when I tried to create a payment I met some problems.

<img width="75%" alt="image" src="https://github.com/user-attachments/assets/e074b9a1-8731-4914-adf2-f8d99b36199b">

Because my service is not a subscription service,so I used `sequenceType: SequenceType.oneoff` and `mandateId` to create a payment.

~~~typescript
paymentInput = {
        description: `Order #12345`,
        amount: 10,
        redirectUrl,
        webhookUrl: `${testHost}/payments/webhook`,
        billingAddress,
        locale: getLocale(billingAddress.country, languageCode) as Locale,
        customerId: customer.Id,
        sequenceType: SequenceType.oneoff,
        method: "creditcard",
        mandateId: input.mandateId,
        metadata: {
          orderId: order.id,
          languageCode: languageCode,
        },
      }
~~~

But after opening the checkout page,I found I need to enter my card again.

<img width="50%" alt="image" src="https://github.com/user-attachments/assets/7bde7ac3-196f-4347-b6ab-39615ecdadf3">

I'm confused because I've passed `mandateId` and `SequenceType.oneoff`,why do I need to enter the card information again...In another way,If I want to use `mandateId`,maybe I have to use `SequenceType.recurring`?But my service is not a subscription service so I can't use `SequenceType.recurring`...

<img width="75%" alt="image" src="https://github.com/user-attachments/assets/a17f0eff-8d66-4aae-b84d-395d5a7c3b46">

Thanks~

**Comment by fjbender** [comment]
Heyo - this is unfortunately a deviation between test and live systems. If you use a live API key, your customer will be redirected to a different page, where entering the card details isn't required anymore. :) 

By the way, as this is not technically an issue with the library but rather the platform itself, I recommend you check out our Developer Discord at https://discord.gg/mollie

**Comment by hooooooouzx** [comment]
Thanks for your reply! @fjbender 

I've joined the Discord Channel,

So in the future payments,in the live mode,I need to use `mandateId` with `SequenceType.oneoff` rather than `SequenceType.recurring`?

**Comment by fjbender** [comment]
Yes, correct!

**Comment by hooooooouzx** [comment]
> Yes, correct!

thanks sir
