### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sidthekidder** [mollie/mollie-api-node#4]
In the examples given for creating and retrieving a payment, we need the payment.id to retrieve the status of a payment. But we can't return any data while giving a 302 redirect with ```response.writeHead(302, { Location: payment.getPaymentUrl() })``` . So what is a good flow to return the paymentid back with the API call? This paymentid is needed to show the current status of the payment on the frontend.
One option is not automatically redirect and return JSON data - any other way?

**Comment by lvgunst** [comment]
Hi @sidthekidder,

I'm not exactly sure what you want to do. After the payment is created you can save the payment ID to your database: https://github.com/mollie/mollie-api-node/blob/master/examples/1-new-payment.js#L55

The payment flow is asynchronous so you can't process the payment status directly after you create the payment and redirect the customer to the payment URL. When the payment changes state Mollie will call your webhook URL. https://github.com/mollie/mollie-api-node/blob/master/examples/2-webhook-verification.js#L42 On the webhook URL you can load the payment and process the state.

More about the [webhook](https://www.mollie.com/en/docs/webhook) and the [payment flow](https://www.mollie.com/en/docs/summary#how-does-the-mollie-api-work).

**Comment by RicardoJ** [comment]
This issue is older than six months. I'll close this issue for now. If you still have a issue, feel free to create a new issue.

Ricardo,
[Mollie](https://www.mollie.com)
