### ISSUE TITLE
setAccessToken is not a function

### ISSUE THREAD

**Issue by Reggino** [mollie/mollie-api-node#50]
Hi,

The node.js code example at [https://www.mollie.com/nl/docs/reference/settlements/list#example](https://www.mollie.com/nl/docs/reference/settlements/list#example) suggests to use

```
mollie.setAccessToken('xxx');
```

on line 4. But ```setAccessToken``` is not a function? I'm not sure this the right place to report this, but you'll probably want to update that example with ```setApiKey```

**Comment by dabroek** [comment]
Correct. Strange that it is in these examples. I will remove them for now. Thank you for reporting.
