### ISSUE TITLE
Update naar v2?

### ISSUE THREAD

**Issue by FranklinWaller** [mollie/mollie-api-node#52]
Mollie lijkt alleen nog gebruik te maken van v1? (Dit project lijkt abandoned te zijn)
Zijn er nog plannen voor v2?

**Comment by dabroek** [comment]
Zeker. We gaan ervoor zorgen dat deze package v2 gaat ondersteunen. Voor nu kun je al gebruik maken van Promises door `npm install mollie-api-node@next` te gebruiken.

**Comment by vernondegoede** [comment]
@FranklinWaller We just released v2 of our official Node API client, which has been upgraded to work with our v2 API.

To install:

```bash
yarn add @mollie/api-client
```

Check out our [migration guide](https://github.com/mollie/mollie-api-node/blob/v2.0.0/MIGRATION.md) for a complete overview of the changes.
