### ISSUE TITLE
missing sequenceType in create payment method.

### ISSUE THREAD

**Issue by anjandaffo** [mollie/mollie-api-node#54]
When I am trying to call create payment method for recurring payment for that I have to set sequenceType:'first' in request body parameter. When I am adding this field getting following error

type=request, message=Unknown field: sequenceType

**Comment by ndijkstra** [comment]
Hi, the Node Mollie Client is using the V1 API of Mollie. There you have to use the `recurringType` parameter instead of `sequenceType`: https://docs.mollie.com/reference/v1/payments-api/create-payment
