### ISSUE TITLE
Upgrade to V2

### ISSUE THREAD

**Issue by joaonice** [mollie/mollie-api-node#55]
Any plans to upgrade the `mollie-api-node` to the Mollie API v2?

**Comment by dabroek** [comment]
Absolutely. We plan to publish a release for the V2 API in the upcoming week (#58).

**Comment by joaonice** [comment]
@dabroek thanks !

**Comment by vernondegoede** [comment]
@joaonice We just released v2 of our official Node API client.

To install:

```bash
yarn add @mollie/api-client
```

Check out our [migration guide](https://github.com/mollie/mollie-api-node/blob/v2.0.0/MIGRATION.md) for a complete overview of the changes.

**Comment by joaonice** [comment]
@vernondegoede thanks !
