### ISSUE TITLE
Webhooks documentation

### ISSUE THREAD

**Issue by adriaanmeuris** [mollie/mollie-api-node#61]
Hi, I'm unable to find examples about webhooks, specifically about the data that's POSTED to the given `webhookUrl`.

[This page pointed me here](https://docs.mollie.com/guides/webhooks#webhooks-for-v2-api-endpoints) (documentation of the Mollie API client), but I'm unable to find any information.

 I've setup a webhook to monitor failed payments of a subscription in the [Create subscription](https://docs.mollie.com/reference/v2/subscriptions-api/create-subscription) API call, but I'm unable to test this since the test-environments only supports happy paths.

**Comment by dabroek** [comment]
The page you refer to clearly states the following:
> The webhook will be called with a single POST-parameter called `id`, which for example will contain the value `tr_d0b0E3EA3v`. You should use that ID to actively fetch the payment to find out about it’s status. This step seems a little cumbersome, but proper security dictates this flow. Since the status is not transmitted in the webhook, fake calls to your webhook will never result in orders being processed without being actually paid.

**Comment by adriaanmeuris** [comment]
right! I was looking for a response type in JSON. For anyone wondering, the `id` is posted to webhookUrl as `application/x-www-form-urlencoded`. Thanks!
