### ISSUE TITLE
Refunded and remaining amount in payment object

### ISSUE THREAD

**Issue by walling** [mollie/mollie-api-node#7]
Please add the fields `amountRefunded` and `amountRemaining` in the [payment object](https://github.com/mollie/mollie-api-node/blob/master/src/lib/mollie/api/object/payment.coffee).

Currently you can't access these fields, when requesting the payment. This is an issue when you receive a `refunded` status via the webhook.

**Comment by StarpTech** [comment]
Any updates?

**Comment by Kenanjl** [comment]
https://github.com/mollie/mollie-api-node/commit/3ddbd3a70805037e575a5f96e227a94a289bb9e7
