### ISSUE TITLE
Add TypeScript type definitions

### ISSUE THREAD

**Issue by cybertim** [mollie/mollie-api-node#70]
Would help a lot while developing.

**Comment by JaapWeijland** [comment]
Please! I need this as well.

**Comment by firstred** [comment]
That would be great to have! The API is strongly typed, so why not make the underlying node library strongly typed as well? Babel 7 has native support for TypeScript.

**Comment by IsaacMe** [comment]
Out of curiosity, are there any further updates on this? It would be amazing if implemented!

**Comment by JFGHT** [comment]
There was a PR but it was closed.

**Comment by Matzu89** [comment]
Hi @vernondegoede ,
Any update on the typescript migration?

**Comment by Pimm** [comment]
This is currently being worked on. 💜

**Comment by vernondegoede** [comment]
We've just released a beta version of the Node API client, which comes with the following changes:

- Added TypeScript type definitions
- Added Orders, Shipments and Captures APIs
- Added ES module in addition to the CommonJS module
- Added QR code support
- Added pagination support
- Added support for embedded resources (`payments`, `refunds`, `chargebacks`, etc.)
