### ISSUE TITLE
Publish to NPM on git tag

### ISSUE THREAD

**Issue by vernondegoede** [mollie/mollie-api-node#75]
We should publish a new version of the client every time we tag a new version in Git to automate our release workflow and make this workflow less dependent on individual persons.

@martijnpolder Can you take care of encrypting the Travis secret?

More information: https://docs.travis-ci.com/user/deployment/npm/#npm-auth-token

**Comment by martijnpolder** [comment]
I sent you an encrypted token through the usual channel for this. Could you verify this works?
