### ISSUE TITLE
No payment id

### ISSUE THREAD

**Issue by tvr3000** [mollie/mollie-api-node#8]
In the docs it says: "The webhook will be called with a single POST-parameter named id "

However, all I get from mollie is a GET request, without the id of the payment.

**Comment by RickWong** [comment]
Hi @tvr3000 you are probably redirecting our POST-webhook to another Location, which turns it into a GET sans `id` parameter. Please check your `webhookUrl` for such redirects.

**Comment by tvr3000** [comment]
Sorry, my mistake. Mixed up the webhookUrl with the redirectUrl.... sloppy!
