### ISSUE TITLE
Empty object response customers.create

### ISSUE THREAD

**Issue by martijnmichel** [mollie/mollie-api-node#92]
When trying to create a customer through firebase cloud functions i get an empty object returned on the client and the customer is never created.

```
exports.createNewCustomerWithSubscription = functions.https.onCall((data, context) => {
    return mollie.customers
        .create({
            name: 'Luke Skywalker',
            email: 'luke@example.org',
            metadata: {
              isJedi: true,
            },
        })
        .then(customer => {
            console.log('Successfully created customer')                
            return customer
               
        })
        .catch(error => {
            // Do some proper error handling.
            console.log('error creating customer')
            return error
          });
})
```

**Comment by vernondegoede** [comment]
Are you initializing a new Mollie client instance somewhere? Like this:

```
const mollie = require('@mollie/api-client')({ apiKey: 'test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM' });
```

**Comment by martijnmichel** [comment]
Yes i am, but not in the functions itself.

**Comment by martijnmichel** [comment]
I am getting an error now at catch.. sorry for the confusion. The error is my console.log

**Comment by vernondegoede** [comment]
I'm not sure if this is related to the Node client, since catch does return an error whenever something goes wrong. 

Are you able to you reproduce this locally (without Firebase Cloud Functions). Firebase Cloud Functions [need to be terminated](https://stackoverflow.com/questions/47154257/cloud-functions-for-firebase-http-timeout/47155902#47155902), otherwise they will trigger a timeout.

**Comment by vernondegoede** [comment]
No problem! Good to hear it's solved 👍

**Comment by martijnmichel** [comment]
I havent solved it at all.. It still doesnt create a customer.

**Comment by vernondegoede** [comment]
My apologies, I misread your comment. What error did the `.catch()` statement return?

**Comment by vernondegoede** [comment]
Sorry, I don't have any experience with Firebase Cloud Functions. 
Can you reproduce this issue without Firebase Cloud Functions (plain Node.js)? If that's the case, can you add the code of the plain Node.js code to this issue?

**Comment by martijnmichel** [comment]
Im not sure I can. Basically the 2 lines above run the code from my first post and return the data. I have alot of other functions running perfectly fine already so i doubt it has something to do with that.

**Comment by martijnmichel** [comment]
The problem might be with this?
Function execution took 143 ms, finished with status code: 204 (no errors)
Function execution took 430 ms, finished with status code: 200 (catch error)

**Comment by martijnmichel** [comment]
Okay, i've solved it. Thanks for helping out.

**Comment by vernondegoede** [comment]
What went wrong exactly?
