### ISSUE TITLE
Docs issue

### ISSUE THREAD

**Issue by JFGHT** [mollie/mollie-api-node#94]
Mollie API docs are awesome yes, but mollie-api-node are not.

I had to dig into the code to learn how to make a payment refund (payments_refunds) which it is not even correct; according to the website you pass to the url a parameter called 'id', not paymentId.

https://docs.mollie.com/reference/v2/refunds-api/create-refund

Please complete the docs.

**Comment by vernondegoede** [comment]
Hi @JFGHT,

I'm sorry to hear that our docs are currently not that helpful. We're working on that (#96). 

I added an example on how to create a refund: https://github.com/mollie/mollie-api-node/blob/improved-examples/examples/refunds/create.js

Hope this helps!

**Comment by vernondegoede** [comment]
We've updated the examples. Let us know if you're missing anything! 👍
